name: 🙋 Question
description: Ask a general question about the project, such as how to use it or for technical details.
title: "[QA]"
labels: ["question"]
assignees:
  - yu13140

body:
  - type: textarea
    attributes:
      label: Your Question
      description: Please describe your question clearly here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: If your question relates to a specific file, line of code, or situation, please provide more information to help us understand.
